### ISSUE TITLE
highlight a flow path for fitting spin waves

### ISSUE THREAD

**Issue by granazhs** [ILLGrenoble/takin#11]
For example with including convolution, data import and anything else necessary on a real case such that the user is guide-lined to reach the final goal without missing any steps
https://spinw.org/tutorials/35tutorial (this is a SpinW example, although not the best way, and only for single crystal, we also need for a powder)

**Comment by tweber-ill** [comment]
Hi again Markos,

Thanks for the ideas!

_Takin_ itself is "unfortunately" too modular, so it's difficult to have step-by-step use cases directly in the software. The convolution module, for example, knows nothing about the magnon module or its internals, it just sees a standardised API.

But I'll continue writing step-by-step [tutorials](https://github.com/ILLGrenoble/takin/wiki) on these more complex workflows.
