### ISSUE TITLE
CLI tool for resolution calculation

### ISSUE THREAD

**Issue by aaeberharter** [ILLGrenoble/takin#14]
A command line interface tool which allows external programs to make use of Takin's implementation for resolution ellipsoid calculation e.g. the Popovici algorithm. I already made a prototype of such a tool, maybe someone can show me how to integrate in the current project so that I can make an effective pull request.
The tool works like this:

`./reso instrument.taz`

Parameters of instrument.taz are read into the `EckParams` struct completely bypassing GUI code. Then the tool enters an endless loop which accepts input to stdin of the form
`algorithm ki kf Q`
e.g.
`pop 1.2 1 0.5`
and prints the resulting resolution matrix into a single line in stdout.
Other programs start a process and communicate with the program via standard I/O.

**Comment by tweber-ill** [comment]
Hello,

thanks, this sound quite useful. The best place for such a tool would probably be under the core/tools directory. Could you please fork the Takin repo, add it, and finally do a pull request? This way, we can have a look and eventually include it. Many thanks!

**Comment by tweber-ill** [comment]
For this job, there's now the Python resolution module which can be used in the command line or included in other projects:

https://github.com/ILLGrenoble/takin/tree/master/core/tools/res_py
