### ISSUE TITLE
Magnetic Dynamics Python Package doesn't build on Mac M3

### ISSUE THREAD

**Issue by nviolini** [ILLGrenoble/takin#22]
I wanted to try out the Magnetic Dynamics Python Package to see if I can leverage it for spin waves calculations.
Unfortunately it seems that I'm running into a local problem when building the package.
Some libraries are not found and I can't seem to solve it on my own.

I attach the warnings/errors log in a separate file.

[takin-log.txt](https://github.com/user-attachments/files/16426361/takin-log.txt)

**Comment by tweber-ill** [comment]
Hello,

indeed, there's some dependencies missing. From what I see in the log, you'll still have to install _Lapack_ / _Lapacke_ (i.e. the Fortran library and its C bindings) as well as _Gemmi_.

- _Gemmi_ you can install by running "bash ../setup/externals/setup_externals_mag.sh" from within the "mag-core" directory.
- _Lapack(e)_ you should be able to find in homebrew. Alternatively, you can build it using the "setup/externals/build_lapacke.sh" script. 

Hope that helps. The building process can be a bit complicated, especially on Mac.

**Comment by tweber-ill** [comment]
Hello,

many thanks for the feedback, glad to hear that it runs now!

The warnings can be ignored, they are either harmless (the C linkage one), are general warnings from _tlibs_ for things that are present in the library but not used in _Magdyn_ (_Faddeeva_ and _QHull_), or about parts on which I'm currently working and which are still disabled by default (_Minuit_ for finding the ground state).
