### ISSUE TITLE
How can we export the 4-D resolution array?

### ISSUE THREAD

**Issue by panziyi1** [ILLGrenoble/takin#24]
It would be a great help if we can export the resolution array for further analysis.

**Comment by tweber-ill** [comment]
Hello,

thanks for the question, could you please add a few details?

- If you need the resolution matrices for specific (h, k, l, E) positions, I recently updated the [_Python_ resolution tools](https://github.com/ILLGrenoble/takin/tree/master/core/tools/res_py) to make it simpler to quickly loop over (h, k, l, E) and export the resolution matrices and their principal axes. If needed, I can give you an example.

- In case you mean exporting the dynamical structure factors used for resolution convolution, this depends on the model used. For example for the magnons, this can be done using the Tools -> Magnetic Dynamics... -> Export tab.

- In case you need to get the results of a resolution convolution on a grid, this is not yet possible, so far the software unfortunately only supports convolutions on 1-d paths or on 2-d maps.

**Comment by panziyi1** [comment]
Thank you for your quick reply. 

I am wondering if I can use this great program to export the numerial representation (array) of the resolution function in a specific spectrometer configuration. I was able to plot a resolution ellipsoid but couldn't find a way to export the 4D coordinates (**Q**, w) and the corresponding values R(**Q**, w).

It seems that we both are talking about the 1st point in your reply. If you would kindly provide some examples or tracks, it would be quite helpful. Thanks !
