### ISSUE TITLE
Adding selection possibility for y-axis (intensity)

### ISSUE THREAD

**Issue by JitaeParkTUM** [ILLGrenoble/takin#3]
In case, there are multiple rows for more than one detector, it would be great to have the possibility to choose a correct detector row manually.

**Comment by tweber-ill** [comment]
Many thanks, I've added this with https://github.com/ILLGrenoble/takin/commit/0f71975ee21ce26762a2b2730fbf06c23fb25f65 .
In the convolution dialog, you can now override the counter and the monitor name using "Options" -> "Counter" / "Monitor".
