### ISSUE TITLE
python export for further plotting spin wave dispersions externally

### ISSUE THREAD

**Issue by granazhs** [ILLGrenoble/takin#8]

**Comment by tweber-ill** [comment]
Hi Markos! Just implemented this, it'll be in one of the next versions.
https://github.com/ILLGrenoble/takin/commit/5c82a63238a62651353a36df385c1671176024c3

Additionally, plots can now also be generated using the py interface, e.g.:
https://github.com/ILLGrenoble/takin/blob/master/data/demos/magnon_Cu2OSeO3/calc_dispersion.py

**Comment by granazhs** [comment]
Hi Tobias, thanks a lot!! Markos
